### ISSUE TITLE
Can zammad have multiple domains for 1 installation

### ISSUE THREAD

**Issue by sandrodz** [zammad/zammad#1533]
Can zammad be accessed via multiple domains? I don't want to install it separately for each project that needs support.

```
version: '3'

services:

  zammad:
    depends_on:
      - zammad-elasticsearch
      - zammad-postgresql
    image: zammad/zammad-docker-compose:zammad
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
    restart: on-failure
    volumes:
      - data-zammad:/home/zammad
    network_mode: "bridge"

  zammad-elasticsearch:
    image: zammad/zammad-docker-compose:zammad-elasticsearch
    labels:
      io.rancher.container.pull_image: always
    restart: always
    network_mode: "bridge"

  zammad-nginx:
    depends_on:
      - zammad
    image: zammad/zammad-docker-compose:zammad-nginx
    labels:
      io.rancher.container.pull_image: always
    links:
      - zammad-railsserver
      - zammad-websocket
    environment:
      VIRTUAL_HOST: zammad.kubikthemes.com
      LETSENCRYPT_HOST: zammad.kubikthemes.com
      LETSENCRYPT_EMAIL: support@kubikthemes.com
    restart: always
    volumes:
      - data-zammad:/home/zammad
    network_mode: "bridge"

  zammad-postgresql:
    image: zammad/zammad-docker-compose:zammad-postgresql
    labels:
      io.rancher.container.pull_image: always
    restart: always
    volumes:
      - ./persist/pgsql:/var/lib/postgresql/data
    network_mode: "bridge"

  zammad-railsserver:
    depends_on:
      - zammad
    image: zammad/zammad-docker-compose:zammad-railsserver
    labels:
      io.rancher.container.pull_image: always
    links:
      - zammad-elasticsearch
      - zammad-postgresql
    depends_on:
      - zammad
    restart: always
    volumes:
      - data-zammad:/home/zammad
    network_mode: "bridge"

  zammad-scheduler:
    depends_on:
      - zammad
    image: zammad/zammad-docker-compose:zammad-scheduler
    labels:
      io.rancher.container.pull_image: always
    links:
      - zammad-elasticsearch
      - zammad-postgresql
    restart: always
    volumes:
      - data-zammad:/home/zammad
    network_mode: "bridge"

  zammad-websocket:
    depends_on:
      - zammad
    image: zammad/zammad-docker-compose:zammad-websocket
    labels:
      io.rancher.container.pull_image: always
    links:
      - zammad-postgresql
      - zammad
    restart: always
    volumes:
      - data-zammad:/home/zammad
    network_mode: "bridge"

volumes:
  data-zammad:
    driver: local
```
