### ISSUE TITLE
Load custom CSS for KB

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2618]
### Infos:

* Used Zammad version: 3.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any 
* Browser + version: any

### Desired behavior:

It should be possible to load custom CSS to the knowledgebase.
This should be done similar to how we do it on our main application via `app/assets/stylesheets/custom/` .

Currently you don't have any chance to manipulate e.g. header links in any way. (see: #2619 )

**Comment by pgassmann** [comment]
We also want to change the HTML of the KB to have the same design as the Website.
With [zammad in docker-compose](https://github.com/zammad/zammad-docker-compose) we can do this now by mounting the `app/views/layouts/knowledge_base.html.erb` on the zammad-railsserver container from outside.

```yaml
  zammad-railsserver:
    command: ["zammad-railsserver"]
    depends_on:
      - zammad-memcached
      - zammad-postgresql
    image: zammad/zammad-docker-compose:zammad-{{ zammad_version }}
    restart: always
    volumes:
      - ./data/zammad-data:/opt/zammad
      - type: bind
        source: ./knowledge_base.html.erb
        target: /opt/zammad/app/views/layouts/knowledge_base.html.erb
        read_only: true
```
