### ISSUE TITLE
Gradual memory consumption increase  (zammad worker and zammad scheduler)

### ISSUE THREAD

**Issue by V-Legendre** [zammad/zammad#5188]
### Used Zammad Version

6.2.0-1

### Environment

- Installation method: docker-compose
- Operating system (if you're unsure: `cat /etc/os-release` ): Ubuntu 22.04.1 LTS
- Database + version:  postgresql 15
- Elasticsearch version: 8.8.0
- Browser + version: N/A

### Actual behaviour

After starting docker-compose zammad services, both the scheduler and railsserver containers memory usages ramp up.
So far, we did not see any garbage collection effect and we had to restart containers to avoid OOM errors.

Is it an expected behaviour from Zammad's end? Should we set strict memory limits for these containers, so that the restart before eating all our servers' resources ?

Please find below an example screenshot and our docker-compose file.

```yaml
---
x-shared:
  zammad-service: &zammad-service
    environment: &zammad-environment
      MEMCACHE_SERVERS: ${MEMCACHE_SERVERS}
      POSTGRESQL_DB: ${POSTGRES_DB}
      POSTGRESQL_HOST: ${POSTGRES_HOST}
      POSTGRESQL_USER: ${POSTGRES_USER}
      POSTGRESQL_PASS: ${POSTGRES_PASS}
      POSTGRESQL_PORT: ${POSTGRES_PORT}
      REDIS_URL: ${REDIS_URL}
      # Allow passing in these variables via .env:
      AUTOWIZARD_JSON:
      AUTOWIZARD_RELATIVE_PATH:
      ELASTICSEARCH_ENABLED:
      ELASTICSEARCH_HOST:
      ELASTICSEARCH_PORT:
      ELASTICSEARCH_SCHEMA:
      ELASTICSEARCH_NAMESPACE:
      ELASTICSEARCH_REINDEX:
      ELASTICSEARCH_SSL_VERIFY:
      NGINX_PORT:
      NGINX_SERVER_NAME:
      NGINX_SERVER_SCHEME:
      POSTGRESQL_DB_CREATE:
      POSTGRESQL_OPTIONS: ${POSTGRESQL_OPTIONS}
      RAILS_TRUSTED_PROXIES:
      ZAMMAD_WEB_CONCURRENCY: 16
      ZAMMAD_SESSION_JOBS_CONCURRENT: 4
      ZAMMAD_PROCESS_SCHEDULED:
      ZAMMAD_PROCESS_DELAYED_JOBS_WORKERS:
    image: ${IMAGE_REPO}:${VERSION}
    restart: ${RESTART}
    volumes:
      - zammad-storage:/opt/zammad/storage
      - zammad-var:/opt/zammad/var
    depends_on:
      - zammad-memcached
      - zammad-redis

services:

  zammad-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2-amd64
    restart: ${RESTART}
    networks:
      - public
    ports:
      - ${ES_PORT}:9200
    volumes:
      - zammad_es_data_01:/usr/share/elasticsearch/data
    environment:
      - node.name=zammad-elasticsearch
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=zammad-elasticsearch
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
    command: >
      /bin/sh -c "./bin/elasticsearch-plugin list |
      grep -q ingest-attachment ||
      ./bin/elasticsearch-plugin install --batch ingest-attachment;
      /usr/local/bin/docker-entrypoint.sh"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD", "curl", "-XGET", "http://localhost:9200"
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  zammad-backup:
    command: ["zammad-backup"]
    logging:
      driver: journald
    depends_on:
      - zammad-railsserver
    entrypoint: /usr/local/bin/backup.sh
    environment:
      <<: *zammad-environment
      BACKUP_TIME: "03:00"
      HOLD_DAYS: "10"
      TZ: Europe/Paris
    image: postgres:${POSTGRES_VERSION}
    restart: ${RESTART}
    volumes:
      - zammad-backup:/var/tmp/zammad
      - zammad-storage:/opt/zammad/storage:ro
      - zammad-var:/opt/zammad/var:ro
      - /home/ubuntu/scripts/backup.sh:/usr/local/bin/backup.sh:ro
    networks:
      - public

  zammad-init:
    <<: *zammad-service
    depends_on:
      zammad-elasticsearch:
        condition: service_healthy
    command: ["zammad-init"]
    logging:
      driver: journald
    restart: on-failure
    user: 0:0
    volumes:
      - zammad-storage:/opt/zammad/storage
      - zammad-var:/opt/zammad/var
    networks:
      - public

  zammad-memcached:
    command: memcached -m 256M
    image: memcached:${MEMCACHE_VERSION}
    restart: ${RESTART}
    networks:
      - public

  zammad-nginx:
    <<: *zammad-service
    command: ["zammad-nginx"]
    depends_on:
      zammad-elasticsearch:
        condition: service_healthy
    logging:
      driver: journald
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=${NGINX_SERVER_NAME}
      - LETSENCRYPT_HOST=${NGINX_SERVER_NAME}
      - VIRTUAL_PORT=8080
      - NGINX_SERVER_SCHEME=https
    volumes:
      - zammad-var:/opt/zammad/var:ro
      - /custom_path/proxy/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - public

  zammad-railsserver:
    <<: *zammad-service
    command: ["zammad-railsserver"]
    depends_on:
      zammad-elasticsearch:
        condition: service_healthy
    logging:
      driver: journald
    networks:
      - public

  zammad-redis:
    image: redis:${REDIS_VERSION}
    logging:
      driver: journald
    restart: ${RESTART}
    volumes:
      - redis-data:/data
    networks:
      - public

  zammad-scheduler:
    <<: *zammad-service
    command: ["zammad-scheduler"]
    logging:
      driver: journald
    networks:
      - public
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: 4.0

  zammad-websocket:
    <<: *zammad-service
    command: ["zammad-websocket"]
    logging:
      driver: journald
    networks:
      - public

  oh-nginx-proxy:
    image: nginxproxy/nginx-proxy
    logging:
      driver: journald
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
      - public

  acme-companion:
    image: nginxproxy/acme-companion
    logging:
      driver: journald
    depends_on: [ oh-nginx-proxy ]
    container_name: nginx-proxy-acme
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - public

volumes:
  redis-data:
    driver: local
  zammad-backup:
    driver: local
  zammad-storage:
    driver: local
  zammad-var:
    driver: local
  zammad_es_data_01:
    driver: local
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:

networks:
  public:
```

<img width="1116" alt="Screenshot 2024-05-24 at 11 41 54" src="https://github.com/zammad/zammad/assets/135222399/1d1d9423-8feb-47aa-b91c-2941a273ed83">

### Expected behaviour

We expect a garbage collection "like" mechanism so that memory consumption is not an issue.

### Steps to reproduce the behaviour

docker-compose up on the same os

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by MrGeneration** [comment]
Please ensure you're on the latest Zammad version. We only support develop and current stable.

**Comment by mgruner** [comment]
Please update to the latest version (6.3.1) of Zammad and let us know if the issue persists.

**Comment by dominic-p** [comment]
Sorry to resurrect an old post, but I'm observing very similar behavior on a fresh install of Zammad on my Kubernetes cluster via the official helm chart.

The scheduler Pod in particular seems to be leaking memory. When I first deployed the chart, the scheduler pod was using about 286Mi of memory. About 30min later it was up to 321Mi. In previous testing I observed it consuming just shy of 700Mi. All of this testing was done on a fresh instance with 0 tickets and only the admin user.

The other pods (railsserver and websocket) are also consuming a decent amount of RAM, but their usage is more static (around 270-280Mi each).

I understand from [this post](https://github.com/zammad/zammad/issues/1271#issuecomment-316947211) that high memory usage is not considered a problem, but this appears to be more like a memory leak. A couple of follow up questions:

1. Are there ways to tune Zammad for a memory constrained environment? I'm already not running elasticsearch or memcached for this reason. I have looked at the [performance tuning docs](https://docs.zammad.org/en/latest/appendix/configure-env-vars.html#performance-tuning), but it wasn't clear to me what env vars might affect memory consumption or how to tune them.

2. Can the scheduler deployment be removed entirely without totally breaking functionality? Or, could it be run only periodically (maybe as a [Kubernetes CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/)), so we can control when we take the memory hit (and memory leaks are mitigated)?

Here's a snippet of the pod spec for version reference:

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/component: zammad-scheduler
    app.kubernetes.io/instance: zammad
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zammad
    app.kubernetes.io/version: 6.5.0-15
    helm.sh/chart: zammad-14.0.1
  name: zammad-scheduler-53d87dk88c-qk2hc
...
spec:
  containers:
    name: zammad-scheduler
    - command:
      - bundle
      - exec
      - script/background-worker.rb
      - start
    image: ghcr.io/zammad/zammad:6
...
status:
  containerStatuses:
  - image: ghcr.io/zammad/zammad:6
    imageID: ghcr.io/zammad/zammad@sha256:1a25a9aee751c0f1a6fdd84e7790264976e0b9fdf8b8d6e9f60b31e83d2cdb13
```
