### ISSUE TITLE
Empty attachments after download

### ISSUE THREAD

**Issue by GoliathLabs** [zammad/zammad#5297]
### Used Zammad Version

Docker Image 6.3.1-109

### Environment

- Installation method: [e.g. source, package] docker-compose
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]: Debian 12
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3] PostgreSQL 16.3
- Elasticsearch version: [e.g. 7.17] 8.14.3
- Browser + version: [e.g. chrome 83, safari 14, firefox 105] Firefox 129.0

```
ELASTICSEARCH_VERSION=8.14.3
IMAGE_REPO=ghcr.io/zammad/zammad
MEMCACHE_SERVERS=zammad-memcached:11211
MEMCACHE_VERSION=1.6.29-alpine
NGINX_PORT=8080
NGINX_EXPOSE_PORT=8080
POSTGRES_DB=zammad_production
POSTGRES_PASS=redacted
POSTGRES_USER=zammad
POSTGRES_HOST=zammad-postgresql
POSTGRES_PORT=5432
POSTGRES_VERSION=16.3-alpine
POSTGRESQL_OPTIONS=?pool=50
REDIS_URL=redis://zammad-redis:6379
REDIS_VERSION=7.2.5-alpine
RESTART=always
# Use a fixed version. You are responsible to update this to newer patch level versions yourself.
VERSION=6.3.1-109
# You can also use floating versions that will give you automatic updates:
# VERSION=6.2     # all patchlevel updates
# VERSION=6       # including minor updates
# VERSION=latest  # all updates of stable versions, including major
# VERSION=develop # bleeding-edge development version
```

### Actual behaviour

I'm encountering an issue where attachments (typically PDF or DOCX files) from incoming email tickets are downloading as 0-byte files Downloading the attachment via an API call works just fine. If I forward the email to my personal mailbox via Zammad, the attachments download without any issues. Additionally, I can still download attachments from older tickets in the system without any problems. I've tried rebuilding the Elasticsearch cluster and even downgraded Zammad to Docker Image version 6.3.0, but the issue persists.

The issue persists across desktop devices and different browser configurations.

I'm unsure what's causing this problem. As I run a small non-profit organization, it's not feasible to keep forwarding attachments to another mailbox just to access them (e.g., invoices). I'm hoping someone can guide me in the right direction or help resolve this issue.

Thank you in advance! And a big thanks for providing Zammad—it has been an invaluable tool for us over the years!

The log in question is attached below. I've tried to download "Invoice 201272.pdf" for reference. It resulted in a 0-byte download to disk.
[production.log](https://github.com/user-attachments/files/16576015/production.log)

CC https://github.com/zammad/zammad-docker-compose/issues/423

### Expected behaviour

Attachments should download just fine.

### Steps to reproduce the behaviour

Just using the standard docker compose deployment with a reverse proxy configuration.

```
---
version: "2"

services:
  zammad-nginx:
    environment:
      - VIRTUAL_HOST=tickets.replaceddomain.org
      - NGINX_SERVER_SCHEME=https
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tickets.entrypoints=https"
      - "traefik.http.routers.tickets.rule=Host(`tickets.replaceddomain.org`)"
      - "traefik.http.routers.tickets.tls=true"
      - "traefik.http.routers.tickets.tls.certresolver=http"
      - "traefik.http.routers.tickets.service=tickets"
      - "traefik.http.routers.tickets.middlewares=default@file"
      - "traefik.http.services.tickets.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

  zammad-elasticsearch:
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

networks:
  proxy:
    external: true
```

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
Hi @GoliathLabs 

we would need some example eml and better reproduction steps. For me, it's not 100% clear what you described in detail when it's working and when it's not working.

**Comment by GoliathLabs** [comment]
> Hi @GoliathLabs
> 
> we would need some example eml and better reproduction steps. For me, it's not 100% clear what you described in detail when it's working and when it's not working.

Hi @dominikklein,

Thank you for the quick response!

Let me provide some more details. We're using Zammad within the standard Docker Compose stack, along with Traefik as a reverse proxy. We’ve set up Traefik using the appropriate override file for the Compose stack (you can find the yml file in my initial comment on this issue).

Here’s the problem we're facing: when a new email is received, Zammad fetches it and creates a new ticket. The email body displays correctly in the desktop web interface. However, when attempting to download an attachment from the ticket, the downloaded file turns out to be empty.
![image](https://github.com/user-attachments/assets/0526f5a9-3f89-4ec8-88ca-e14f59f3765a)
![image](https://github.com/user-attachments/assets/21571a3e-7ee5-46d2-804c-8d60411584a2)

The dev console doesn't log any errors when downloading the file. The download URL seems to be fine as well (https://tickets.redacteddomain.org/api/v1/ticket_attachment/10479/14039/32228?disposition=attachment)
![image](https://github.com/user-attachments/assets/5fe3eb5e-2dc7-4a37-b569-227deea2ee30)
The server logs show the GET request, similar to the "Invoice" log I mentioned in my initial issue description.

I’ve also attached an example .eml file below (zipped, as GitHub doesn’t allow direct attachment of .eml files). The attachment appears to be saved correctly with its contents. This would explain why the download works as expected on a mobile browser.
[ticket-6510472-14039.zip](https://github.com/user-attachments/files/16590605/ticket-6510472-14039.zip)

This time, the attachment cannot be downloaded via the mobile interface as well.

Is there any other information I can provide you?

Thank you in advance! 😄

**Comment by dominikklein** [comment]
Is it the same also for attachments which are added in the Zammad-UI (e.g. adding a new article)?

For me this looks more like a configuration problem of the environment. Can you try to download it directly via a direct API call? For example with curl (keep in mind to set correct headers for authentication) or another tool.

In general this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by GoliathLabs** [comment]
> Is it the same also for attachments which are added in the Zammad-UI (e.g. adding a new article)?
> 
> For me this looks more like a configuration problem of the environment. Can you try to download it directly via a direct API call? For example with curl (keep in mind to set correct headers for authentication) or another tool.
> 
> In general this seems to be a technical question. Please note that this repository is the wrong place for technical questions. Instead, please refer the Zammad community over at: [community.zammad.org](https://community.zammad.org) .
> 
> In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!
> 
> If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: [zammad.com/pricing#selfhosted](https://zammad.com/pricing#selfhosted) _If you're paying customer already, please consult your Zammad support for assistance! :-)_

Hi,
I can download files which I've uploaded via the Zammad-UI. The API call works as well.

I'll transfer the question over to the Zammad community. Thank you for your time!

**Comment by GoliathLabs** [comment]
In the meantime, I managed to resolve the issue. It turns out we are using Traefik as a reverse proxy for the instance, and the problem was caused by incorrect headers in the configuration. These headers were preventing attachment downloads. Once I commented out the relevant parameters, everything worked as expected.

The headers I excluded from the configuration are as follows:
```
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        frameDeny: true
        referrerPolicy: same-origin
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
```

Hope that helps anyone facing the same problem :)
